# Generated by Django 3.0.4 on 2020-03-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_coronavirusstatus_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coronavirusstatus',
            name='country',
            field=models.CharField(max_length=15),
        ),
    ]
