# Generated by Django 3.0.4 on 2020-03-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0004_auto_20200326_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='coronavirusstatus',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
